### ISSUE TITLE
post-link script failed for this packcage

### ISSUE THREAD

**Issue by LinkMedicine** [Bioconductor/GenomeInfoDbData#3]
I am new to using conda. I am trying to set up an environment on liunix  and I ran into an issue.
（for some reasons ,I have to use tsinghua mirror）

**ERROR conda.core.link:_execute(699): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0
location of failed script: /THL4/home/jli02/miniconda3/envs/458/bin/.bioconductor-genomeinfodbdata-post-link.sh**
==> script messages <==
<None>
==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 284d8e9620b22879410faf66007b3852:
https://bioconductor.org/packages/3.13/data/annotation/src/contrib/GenomeInfoDbData_1.2.6.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.6.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.6_src_all.tar.gz
stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) Received HTTP code 403 from proxy after CONNECT
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) Received HTTP code 403 from proxy after CONNECT
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) Received HTTP code 403 from proxy after CONNECT

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 317, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 346, in handle_txn
    unlink_link_transaction.execute()
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 250, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 713, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0
location of failed script: /THL4/home/jli02/miniconda3/envs/458/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 284d8e9620b22879410faf66007b3852:
https://bioconductor.org/packages/3.13/data/annotation/src/contrib/GenomeInfoDbData_1.2.6.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.6.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.6_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) Received HTTP code 403 from proxy after CONNECT
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) Received HTTP code 403 from proxy after CONNECT
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) Received HTTP code 403 from proxy after CONNECT

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/THL4/home/jli02/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1113, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1056, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/__init__.py", line 1471, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/__init__.py", line 1594, in handle
    if (not self.disabled) and self.filter(record):
  File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/__init__.py", line 802, in filter
    result = f.filter(record)
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/gateways/logging.py", line 60, in filter
    record.msg = record.msg % new_args
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 126, in __repr__
    errs.append(e.__repr__())
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 65, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 84, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 739

**Comment by hpages** [comment]
Please report to the Bioconda folks. Looks like an issue with their post-link script. Thanks

**Comment by hpages** [comment]
I'm assuming this has been addressed by now. Please let us know if you're still running into this problem. Thanks!
